# © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

- type: entity
  name: Дипломат NanoTrasen
  id: NanoTrasenCentCommDiplomat
  components:
    - type: Sprite
      sprite: SS220/Markers/jobs.rsi
      state: centcommdiplomat
    - type: RandomHumanoidSpawner
      settings: NanoTrasenCentCommDiplomat

- type: randomHumanoidSettings
  id: NanoTrasenCentCommDiplomat
  speciesBlacklist: [ Arachnid, Diona, Dwarf, Reptilian, Skeleton, SlimePerson, Vox, Moth, Felinid ]
  components:
    - type: GhostRole
      name: ghost-role-information-centcom-official-name
      description: ghost-role-information-centcom-official-description
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ NanoTrasenCentCommDiplomatGear ]

- type: playTimeTracker
  id: JobCentcommDiplomat

- type: job
  id: NanoTrasenCentCommDiplomat
  name: job-name-centcomoff
  description: job-description-centcomoff
  setPreference: false
  startingGear: NanoTrasenCentCommDiplomatGear
  icon: "JobIconNanotrasen"
  playTimeTracker: JobCentcommDiplomat
  supervisors: job-supervisors-centcom
  canBeAntag: false
  radioBold: true
  accessGroups:
  - AllAccess

- type: startingGear
  id: NanoTrasenCentCommDiplomatGear
  equipment:
    jumpsuit: ClothingUniformNanoTrasenNavyOfficer
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatBeretNanoTrasenOfficer
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesLatex
    id: CentcomDiplomatPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: BoxFolderBlack
    pocket2: NTbaton
    belt: WeaponPulsePistol

